import { sqliteTable, text, integer, primaryKey, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const reviewers=sqliteTable('reviewers',{userId:text('user_id').primaryKey(),email:text('email').notNull(),displayName:text('display_name').notNull(),slot:integer('slot').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('reviewer_slots').on(t.slot),uniqueIndex('reviewer_emails').on(t.email)]);
export const sources=sqliteTable('sources',{id:text('id').primaryKey(),position:integer('position').notNull(),subject:text('subject').notNull(),body:text('body').notNull(),sourceJson:text('source_json').notNull(),sha256:text('sha256').notNull(),allocation:text('allocation').notNull(),commonBlind:integer('common_blind').notNull(),ownerSlot:integer('owner_slot').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('source_positions').on(t.position)]);
export const reviews=sqliteTable('reviews',{sourceId:text('source_id').notNull().references(()=>sources.id),userId:text('user_id').notNull().references(()=>reviewers.userId),annotationJson:text('annotation_json').notNull(),status:text('status').notNull(),revision:integer('revision').notNull(),activeMs:integer('active_ms').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),submittedAt:text('submitted_at')},t=>[primaryKey({columns:[t.sourceId,t.userId]})]);
export const revisions=sqliteTable('review_revisions',{id:text('id').primaryKey(),sourceId:text('source_id').notNull(),userId:text('user_id').notNull(),revision:integer('revision').notNull(),annotationJson:text('annotation_json').notNull(),status:text('status').notNull(),createdAt:text('created_at').notNull()});
export const calibrationRoundSources=sqliteTable('calibration_round_sources',{roundId:text('round_id').notNull(),sourceId:text('source_id').notNull().references(()=>sources.id),sourceSha256:text('source_sha256').notNull(),position:integer('position').notNull(),createdAt:text('created_at').notNull()},t=>[primaryKey({columns:[t.roundId,t.sourceId]})]);
export const directReviews=sqliteTable('direct_reviews',{sourceId:text('source_id').notNull().references(()=>sources.id),userId:text('user_id').notNull().references(()=>reviewers.userId),annotationJson:text('annotation_json').notNull(),status:text('status').notNull(),revision:integer('revision').notNull(),activeMs:integer('active_ms').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),submittedAt:text('submitted_at')},t=>[primaryKey({columns:[t.sourceId,t.userId]})]);
export const directRevisions=sqliteTable('direct_review_revisions',{id:text('id').primaryKey(),sourceId:text('source_id').notNull(),userId:text('user_id').notNull(),revision:integer('revision').notNull(),annotationJson:text('annotation_json').notNull(),status:text('status').notNull(),createdAt:text('created_at').notNull()});
// v1.1 starts fresh; v1 direct records above are preserved without conversion.
export const directLabelReviews=sqliteTable('direct_label_reviews',{sourceId:text('source_id').notNull().references(()=>sources.id),userId:text('user_id').notNull().references(()=>reviewers.userId),annotationJson:text('annotation_json').notNull(),status:text('status').notNull(),revision:integer('revision').notNull(),activeMs:integer('active_ms').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),submittedAt:text('submitted_at')},t=>[primaryKey({columns:[t.sourceId,t.userId]})]);
export const directLabelRevisions=sqliteTable('direct_label_review_revisions',{id:text('id').primaryKey(),sourceId:text('source_id').notNull(),userId:text('user_id').notNull(),revision:integer('revision').notNull(),annotationJson:text('annotation_json').notNull(),status:text('status').notNull(),createdAt:text('created_at').notNull()});
