'use client';
import {useEffect,useRef,useState} from 'react';
import {blank,cp,deriveLabels,derivedLabelHelp,eventStates,rules,validateAnnotation} from '../lib/annotation';
import {authored,exactMatches,guide,kinds,missingRoles,roleHints,roleLabels,stateLabels} from '../lib/guidance';
const human=(s:string)=>s.replaceAll('_',' ').toLowerCase();

async function api(path:string,opts?:RequestInit):Promise<any>{const r=await fetch(path,{cache:'no-store',...opts}),v:any=await r.json();if(!r.ok)throw Object.assign(new Error([v.error,...(v.errors||[])].join('\n')),{status:r.status});return v;}
export default function Home(){
 const [queue,Q]=useState<any[]>([]),[user,U]=useState<any>(null),[source,S]=useState<any>(null),[a,A]=useState<any>(null),[status,T]=useState('new'),[notice,N]=useState('Loading your queue…'),[error,E]=useState(''),[busy,B]=useState(false),[auth,H]=useState(false),[filter,F]=useState('unfinished'),[showRules,R]=useState(false),[attest,C]=useState(false),[target,G]=useState('scope'),[role,L]=useState('EVENT_ANCHOR'),[actor,K]=useState('PERSON'),[manual,M]=useState(''),[field,D]=useState('current_message'),[selected,V]=useState<any>(null),[matches,W]=useState<any[]>([]),[existing,X]=useState('');
 const [step,setStep]=useState(0),[scopeTouched,touchScope]=useState(false),[progress,setProgress]=useState<any>(null);const guideDialog=useRef<HTMLDialogElement>(null);
 const reviewPanel=useRef<HTMLElement>(null);const body=useRef<HTMLPreElement>(null),subject=useRef<HTMLHeadingElement>(null),state=useRef<any>({a:null,source:null,revision:0,status:'new',dirty:false}),saving=useRef(false),loading=useRef(false),active=useRef(0),lastActive=useRef(Date.now());const frozen=status==='submitted';
 function edit(fn:(x:any)=>void){if(state.current.status==='submitted'||state.current.submitting)return;const x=structuredClone(state.current.a);fn(x);state.current.a=x;state.current.dirty=true;A(x);N('Unsaved changes');E('');}
 async function refresh(){const v=await api('/api/queue');Q(v.queue);U(v.user);return v.queue;}
 async function save(submit=false){if(saving.current||!state.current.source||state.current.status==='submitted')return false;if(!state.current.dirty&&!submit)return true;saving.current=true;state.current.submitting=submit;B(true);E('');const snapshot=structuredClone(state.current.a);try{const v=await api('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source_id:state.current.source.source_id,annotation:snapshot,revision:state.current.revision,status:submit?'submitted':'draft',human_attestation:submit&&attest,active_ms:active.current})});active.current=0;state.current.revision=v.revision;state.current.status=v.status;state.current.dirty=JSON.stringify(state.current.a)!==JSON.stringify(snapshot);T(v.status);N(state.current.dirty?'Unsaved changes':submit?'Submitted · frozen':'Saved just now');await refresh();return true;}catch(e:any){E(e.message);N('Save failed · your changes remain on this page');return false;}finally{saving.current=false;state.current.submitting=false;B(false);}}
 async function open(id:string){if(loading.current||saving.current)return;if(state.current.dirty&&!await save())return;loading.current=true;B(true);E('');try{const v=await api('/api/email?id='+encodeURIComponent(id)),x=v.annotation||blank(v.source);state.current={a:x,source:v.source,revision:v.revision,status:v.status,dirty:false};S(v.source);A(x);T(v.status);setStep(v.status==='submitted'?2:0);touchScope(!!v.annotation);G('scope');V(null);W([]);M('');C(false);active.current=0;N(v.status==='submitted'?'Submitted · frozen':v.status==='draft'?'Saved draft':'New · start with relevance');}catch(e:any){E(e.message);}finally{loading.current=false;B(false);}}
 useEffect(()=>{let live=true;refresh().then(q=>{if(live){N(q.length?'Your independent queue is ready':'No emails assigned yet. The owner can import the frozen calibration queue.');if(q.length)void open((q.find((x:any)=>x.status!=='submitted')||q[0]).id);}}).catch(e=>{if(live){E(e.message);H(e.status===401);N('Sign in to start reviewing');}});return()=>{live=false;};},[]);
 useEffect(()=>{const activity=()=>{lastActive.current=Date.now();};const timer=setInterval(()=>{if(document.visibilityState==='visible'&&Date.now()-lastActive.current<60000&&state.current.source&&state.current.status!=='submitted')active.current+=1000;},1000),autosave=setInterval(()=>{if(state.current.dirty&&!loading.current)void save();},10000);const unload=(e:BeforeUnloadEvent)=>{if(state.current.dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('pointerdown',activity);window.addEventListener('keydown',activity);window.addEventListener('beforeunload',unload);return()=>{clearInterval(timer);clearInterval(autosave);window.removeEventListener('pointerdown',activity);window.removeEventListener('keydown',activity);window.removeEventListener('beforeunload',unload);};},[]);
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const life=new AbortController();Promise.resolve(mc.registerTool({name:'read_labeling_rules',title:'Read labeling rules',description:'Read the visible guide. Does not read emails or create human annotations.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input:any)=>{if(!input||Object.keys(input).length)throw new Error('No arguments expected.');return {rules:guide.map(([title,text])=>({title,text}))};}},{signal:life.signal})).catch(()=>{});return()=>life.abort();},[]);
 function capture(f:string){if(frozen||step===2)return;const node=f==='subject'?subject.current:body.current,s=window.getSelection();if(!node||!s?.rangeCount||s.isCollapsed)return;const r=s.getRangeAt(0);if(!node.contains(r.startContainer)||!node.contains(r.endContainer))return;const before=document.createRange();before.selectNodeContents(node);before.setEnd(r.startContainer,r.startOffset);const start=cp(before.toString()).length,end=start+cp(r.toString()).length;if(f==='current_message'&&!authored(source,start,end)){E('Choose the normal message text. Faded signatures and older text cannot be used as evidence.');V(null);return;}V({field:f,start,end,text:cp(source[f]).slice(start,end).join('')});W([]);E('');}
 function find(){const found=exactMatches(source,field,manual);W(found);V(found.length===1?found[0]:null);E(found.length?'':'Those exact words were not found in the allowed message text. Copy them from the message or subject.');}

 function add(sel:any,evidenceRole=role){if(!sel||frozen)return;const type=target==='scope'?'OTHER':rules.role_types[evidenceRole][0];if(sel.field==='current_message'&&!source.authored_ranges.some((r:any)=>sel.start>=r.start&&sel.end<=r.end)){E('Choose authored words outside quoted history and signatures.');return;}if(target!=='scope'&&evidenceRole==='EVENT_ANCHOR'&&sel.field!=='current_message'){E('Event words must come from the current message.');return;}edit(x=>{let s=x.spans.find((z:any)=>z.source_id===source.source_id&&z.field===sel.field&&z.start===sel.start&&z.end===sel.end&&z.type===type);if(!s){s={id:'s_'+crypto.randomUUID(),source_id:source.source_id,...sel,type,...(type==='ACTOR'?{actor_kind:rules.role_actor_kind?.[evidenceRole]?.[0]||actor}:{})};x.spans.push(s);}if(target==='scope'){if(!x.scope.evidence_span_ids.includes(s.id))x.scope.evidence_span_ids.push(s.id);}else if(!x.event_span_links.some((l:any)=>l.event_id===target&&l.span_id===s.id&&l.role===evidenceRole))x.event_span_links.push({event_id:target,span_id:s.id,role:evidenceRole,certainty:'SUPPORTED'});});V(null);M('');W([]);}
 function addEvent(kind:string){const id='e_'+crypto.randomUUID();edit(x=>x.events.push({id,kind,state:eventStates[kind][0],certainty:'SUPPORTED',...(kind==='ACTION'?{action_class:'OPERATIONAL'}:{}),...(kind==='DOCUMENT'?{document_class:'PROJECT_DELIVERABLE'}:{})}));G(id);L('EVENT_ANCHOR');}
 function removeSpan(id:string){edit(x=>{x.spans=x.spans.filter((s:any)=>s.id!==id);x.scope.evidence_span_ids=x.scope.evidence_span_ids.filter((z:string)=>z!==id);x.event_span_links=x.event_span_links.filter((l:any)=>l.span_id!==id);x.event_relations=x.event_relations.filter((r:any)=>!r.evidence_span_ids.includes(id));});}

 async function importFile(file:File){B(true);try{const rows=(await file.text()).split(/\r?\n/).filter(Boolean).map(x=>JSON.parse(x));for(let i=0;i<rows.length;i+=25){await api('/api/admin/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(rows.slice(i,i+25))});N(`Imported ${Math.min(i+25,rows.length)} / ${rows.length}`);}const q=await refresh();if(q.length&&!source)await open(q[0].id);}catch(e:any){E(e.message);}finally{B(false);}}

 useEffect(()=>{if(source)window.scrollTo({top:0,behavior:'instant'});},[source?.source_id]);
 useEffect(()=>{if(step>0&&window.matchMedia('(max-width:950px)').matches)reviewPanel.current?.scrollIntoView({block:'start',behavior:'instant'});},[step]);
 useEffect(()=>{const dialog=guideDialog.current;if(showRules&&!dialog?.open)dialog?.showModal();if(!showRules&&dialog?.open)dialog.close();},[showRules]);
 function friendlyError(message:string){let text=message.replace('$.scope.reason is required','Add a short reason for your relevance choice.').replace('Uncertainty or unresolved prior events require another review.','Keep “Needs another review” selected while a label or earlier event is unclear.').replace('Explain what needs another review.','Write what you are unsure about in the review note.');for(const e of a?.events||[])text=text.replaceAll(`${e.kind} ${e.id}`,kinds[e.kind].title);for(const span of a?.spans||[])text=text.replaceAll(span.id,`“${span.text}”`);return text;}
 function chooseScope(value:string){if(value==='NON_PROJECT'&&a.events.length&&!window.confirm('This removes your project labels. Keep your relevance explanation?'))return;edit(x=>{x.scope.value=value;if(value==='NON_PROJECT'){x.events=[];x.event_span_links=[];x.event_relations=[];x.spans=x.spans.filter((s:any)=>x.scope.evidence_span_ids.includes(s.id));}if(value==='UNCERTAIN')x.needs_review=true;});touchScope(true);G('scope');V(null);}
 function chooseRole(eventId:string,evidenceRole:string){G(eventId);L(evidenceRole);if(rules.role_actor_kind?.[evidenceRole])K(rules.role_actor_kind[evidenceRole][0]);V(null);W([]);}
 function removeEvent(id:string){edit(x=>{x.events=x.events.filter((e:any)=>e.id!==id);x.event_span_links=x.event_span_links.filter((l:any)=>l.event_id!==id);x.event_relations=x.event_relations.filter((r:any)=>r.source_event_id!==id);const used=new Set([...x.scope.evidence_span_ids,...x.event_span_links.map((l:any)=>l.span_id),...x.event_relations.flatMap((r:any)=>r.evidence_span_ids)]);x.spans=x.spans.filter((s:any)=>used.has(s.id));});G('scope');V(null);}
 function flagFollowUp(){if(!selected||!ev||frozen)return;if(selected.field!=='current_message'||!authored(source,selected.start,selected.end)){E('Highlight the author’s current reminder words.');return;}edit(x=>{let span=x.spans.find((s:any)=>s.field===selected.field&&s.start===selected.start&&s.end===selected.end&&s.type==='EVENT_TRIGGER');if(!span){span={id:'s_'+crypto.randomUUID(),source_id:source.source_id,...selected,type:'EVENT_TRIGGER'};x.spans.push(span);}if(!x.event_span_links.some((l:any)=>l.event_id===ev.id&&l.span_id===span.id&&l.role==='EVENT_ANCHOR'))x.event_span_links.push({event_id:ev.id,span_id:span.id,role:'EVENT_ANCHOR',certainty:'SUPPORTED'});if(!x.event_relations.some((r:any)=>r.source_event_id===ev.id&&r.kind==='FOLLOW_UP_OF'&&!r.target))x.event_relations.push({id:'r_'+crypto.randomUUID(),source_event_id:ev.id,kind:'FOLLOW_UP_OF',target:null,certainty:'SUPPORTED',evidence_span_ids:[span.id]});x.needs_review=true;});V(null);setStep(2);N('Follow-up flagged. Explain the missing earlier event in your review note.');}
 async function submitNext(){const errors=validateAnnotation(a,source);if(errors.length){E(errors.map(friendlyError).join('\n'));return;}if(!attest){E('Confirm that you reviewed this email independently.');return;}const currentId=source.source_id;if(await save(true)){const q=await refresh(),next=q.find((x:any)=>x.status!=='submitted'&&x.id!==currentId);if(next)await open(next.id);else N('All your assigned emails are submitted. Thank you.');}}
 const ev=a?.events.find((e:any)=>e.id===target),roles=ev?Object.keys(roleLabels).filter(r=>rules.role_event_kinds[r].includes(ev.kind)):[],done=queue.filter(q=>q.status==='submitted').length,visible=queue.filter(q=>filter==='all'||(filter==='unfinished'?q.status!=='submitted':q.status===filter));
 const currentIndex=queue.findIndex(q=>q.id===source?.source_id),nextEmail=queue.find(q=>q.status!=='submitted'&&q.id!==source?.source_id);
 const errors=a&&source?validateAnnotation(a,source):[],missing=ev?missingRoles(a,ev):[],derivedLabels=a&&source&&!errors.length&&!a.needs_review?deriveLabels(a):[];
 const authoredEnd=source?.authored_ranges?.length&&source.authored_ranges[0].start===0?Math.max(...source.authored_ranges.map((r:any)=>r.end)):cp(source?.current_message||'').length;
 const text=cp(source?.current_message||''),history=text.slice(authoredEnd).join('')||source?.thread_context||'';
 const boundaries=[...new Set<number>([0,authoredEnd,...(source?.authored_ranges||[]).flatMap((r:any)=>[r.start,r.end]),...(a?.spans||[]).filter((s:any)=>s.field==='current_message').flatMap((s:any)=>[s.start,s.end])])].filter(n=>n>=0&&n<=authoredEnd).sort((x,y)=>x-y);
 const evidenceTools=(!frozen&&step<2)?<div className="evidence-tools" id="evidence-tools">
  <div className="evidence-heading"><strong>{target==='scope'?'Evidence for project relevance':roleLabels[role]}</strong><span>Highlight words in the email</span></div>
  <p className="hint">{target==='scope'?'Choose a short phrase supporting your relevance choice, if one is present. Do not invent evidence when context is missing.':roleHints[role]||'Add only words explicitly present. This detail is optional unless marked Required.'}</p>
  {selected?<div className="selection"><blockquote>{selected.text}</blockquote><button className="primary" onClick={()=>add(selected)}>Use these words</button><button className="quiet" onClick={()=>V(null)}>Clear</button></div>:<p className="selection-empty">Drag over the exact words in the message. Your selection will appear here.</p>}
  <details><summary>Prefer to copy and paste?</summary><div className="form-row"><label>Look in<select value={field} onChange={e=>{D(e.target.value);W([]);V(null);}}><option value="current_message">Current message</option><option value="subject">Subject</option></select></label><label>Paste exact words<input value={manual} onChange={e=>M(e.target.value)} placeholder="Copy a short phrase"/></label></div><button onClick={find} disabled={!manual}>Find this phrase</button>{matches.length>1&&<div className="occurrences"><p>This phrase appears more than once. Choose the occurrence you mean:</p>{matches.map(m=><button key={m.start} onClick={()=>V(m)}>{cp(source[m.field]).slice(Math.max(0,m.start-25),m.end+25).join('')}</button>)}</div>}</details>
  {ev&&a.spans.some((s:any)=>rules.role_types[role].includes(s.type))&&<details><summary>Use words you already highlighted</summary><label>Saved evidence<select value={existing} onChange={e=>X(e.target.value)}><option value="">Choose a phrase</option>{a.spans.filter((s:any)=>rules.role_types[role].includes(s.type)).map((s:any)=><option key={s.id} value={s.id}>{s.text}</option>)}</select></label><button disabled={!existing||!a.spans.some((s:any)=>s.id===existing&&rules.role_types[role].includes(s.type))} onClick={()=>edit(x=>{if(!x.event_span_links.some((l:any)=>l.event_id===target&&l.span_id===existing&&l.role===role))x.event_span_links.push({event_id:target,span_id:existing,role,certainty:'SUPPORTED'});})}>Connect phrase</button></details>}
 </div>:null;
 return <div className="app">
  <header className="topbar"><div className="brand"><span className="brandmark" aria-hidden="true">F</span><div><strong>FYP Review Room</strong><small>Your independent email review</small></div></div><div className="header-actions"><span className="private-badge">Private review</span>{user&&<span className="identity">{user.name}</span>}<button onClick={()=>R(true)}>Help & examples</button></div></header>
  <div className="statusbar"><span role="status" aria-live="polite">{notice}</span><div className="progress-summary"><span>{done} of {queue.length} submitted</span><progress value={done} max={Math.max(1,queue.length)} aria-label="Your review progress"/></div></div>
  {error&&<div className="error" role="alert"><div><strong>Here’s what to fix</strong><pre>{error}</pre></div><button onClick={()=>E('')} aria-label="Dismiss message">Dismiss</button></div>}
  {auth?<section className="empty"><h1>Your private review space</h1><p>Sign in with your own ChatGPT account to see your emails and saved drafts.</p><a className="primary button" href="/signin-with-chatgpt?return_to=%2F">Sign in with ChatGPT</a></section>:<main className="workspace">
   <aside className="queue"><details className="queue-disclosure" open><summary>Your emails <span>{queue.length}</span></summary><label>Show<select value={filter} onChange={e=>F(e.target.value)}><option value="unfinished">To finish</option><option value="draft">Saved drafts</option><option value="submitted">Submitted</option><option value="all">All emails</option></select></label><div className="queue-list">{visible.map((q,i)=><button disabled={busy} aria-current={source?.source_id===q.id?'true':undefined} className={'queue-item'+(source?.source_id===q.id?' selected':'')} key={q.id} onClick={()=>void open(q.id)}><span className="queue-number">{queue.findIndex(x=>x.id===q.id)+1}</span><span><strong>{q.subject||'(No subject)'}</strong><small>{q.status==='new'?'Not started':q.status==='draft'?'Saved draft':'Submitted'}</small></span></button>)}{!visible.length&&<p className="hint">No emails in this view.</p>}</div></details>
   {user?.isAdmin&&<details className="owner-tools"><summary>Study controls</summary><p>Import sources or check aggregate progress. Individual answers stay hidden until the shared round is complete.</p><label>Import frozen queue<input type="file" accept=".jsonl,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);}}/></label><button onClick={async()=>{try{setProgress(await api('/api/admin/progress'));}catch(e:any){E(e.message);}}}>View study progress</button>{progress&&<div className="study-progress">{progress.progress.map((p:any)=><p key={p.status}>{p.status==='submitted'?'Submitted reviews':'Saved drafts'}: <strong>{p.count}</strong></p>)}<p>Answers remain hidden.</p></div>}<button onClick={async()=>{try{const payload=await api('/api/admin/export');const url=URL.createObjectURL(new Blob([JSON.stringify(payload)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='fyp-blind-reviews-for-adjudication.json';link.click();URL.revokeObjectURL(url);N('Private review export downloaded.');}catch(e:any){E(e.message);}}}>Download completed blind round</button></details>}</aside>
   {source&&a?<div className="work">
    <section className="email card"><div className="section-heading"><span className="eyebrow">Email {currentIndex+1} of {queue.length}</span><span className="muted">Read the current message</span></div><h1 ref={subject} onMouseUp={()=>capture('subject')} onKeyUp={()=>capture('subject')}>{source.subject||'(No subject)'}</h1><p className="reading-tip">Read first. Then highlight exact words when the form asks for evidence.</p><pre ref={body} onMouseUp={()=>capture('current_message')} onKeyUp={()=>capture('current_message')} tabIndex={0} aria-label="Current email message; select words for evidence" className="email-body">{boundaries.slice(0,-1).map((start,i)=>{const end=boundaries[i+1],allowed=authored(source,start,end),saved=allowed&&a.spans.some((s:any)=>s.field==='current_message'&&s.start<=start&&s.end>=end);return <span key={start} className={!allowed?'excluded-text':saved?'saved-highlight':undefined} title={!allowed?'Reference only; not labeling evidence':saved?'Already used as evidence':undefined}>{text.slice(start,end).join('')}</span>;})}</pre>{source.authored_ranges.length>1&&<p className="hint">Faded lines are reference only. Use the normal text as labeling evidence.</p>}
    {selected&&!frozen&&step<2&&<div className="selection quick-selection"><small>For {target==='scope'?'project relevance':kinds[ev?.kind]?.title+' · '+roleLabels[role]}</small><blockquote>{selected.text}</blockquote><button className="primary" onClick={()=>add(selected)}>Use these words</button><button className="quiet" onClick={()=>V(null)}>Clear</button></div>}
    {history&&<details className="history"><summary>Older or excluded text — reference only</summary><p className="hint">Use this to understand context. Do not label it as a new act by the current author.</p><pre className="context">{history}</pre></details>}</section>
    <section ref={reviewPanel} className="review-panel card"><nav className="steps" aria-label="Review steps">{['Relevance','Label message','Check & submit'].map((name,i)=><button key={name} aria-current={step===i?'step':undefined} className={step===i?'active':''} onClick={()=>{setStep(i);V(null);if(i===0)G('scope');else if(i===1&&a.events.length&&target==='scope')chooseRole(a.events[0].id,'EVENT_ANCHOR');}}><span>{i+1}</span>{name}</button>)}</nav>
    {frozen&&<div className="locked-note">This review is submitted and locked. You can read it, then move to the next email.</div>}
    {step===0&&<div className="step-content"><h2>Is this message about project work?</h2><p className="hint">Look for a bounded goal, deliverable, coordinated workstream, milestone or meeting. The word “project” need not appear. A contract, data request or staffing email alone does not prove project work; if the connection is unclear, choose “Not sure.”</p><div className="scope-options">{[['PROJECT','Project work','A specific initiative, workstream, milestone or deliverable'],['NON_PROJECT','Not project work','Routine operations, personal matters or clearly unrelated business'],['UNCERTAIN','Not sure','The message does not show whether this is a defined initiative']].map(([v,title,description])=><button key={v} disabled={frozen} aria-pressed={scopeTouched&&a.scope.value===v} className={scopeTouched&&a.scope.value===v?'active':''} onClick={()=>chooseScope(v)}><strong>{title}</strong><span>{description}</span></button>)}</div><label>Your reason<textarea disabled={frozen} value={a.scope.reason} onChange={e=>{touchScope(true);edit(x=>x.scope.reason=e.target.value);}} placeholder="In one sentence, what makes this project work, unrelated, or unclear?"/></label><div className="chips">{a.scope.evidence_span_ids.map((id:string)=>{const s=a.spans.find((s:any)=>s.id===id);return s?<span className="chip" key={id}>{s.text}<button disabled={frozen} aria-label={'Remove relevance evidence '+s.text} onClick={()=>removeSpan(id)}>×</button></span>:null;})}</div>{evidenceTools}<div className="step-actions"><button onClick={()=>R(true)}>See an example</button><button className="primary" disabled={!scopeTouched||!a.scope.reason.trim()} onClick={()=>{setStep(a.scope.value==='NON_PROJECT'?2:1);V(null);}}>Continue</button></div></div>}
    {step===1&&<div className="step-content"><h2>What does the author do in this message?</h2><p className="hint">Add only the acts stated in the current message. More than one label is allowed. Some messages have none.</p>{a.scope.value==='NON_PROJECT'?<div className="tip-box">You chose “Not project work”, so no project labels are needed. Continue to the final check.</div>:<><div className="kind-picker">{Object.entries(kinds).map(([kind,item])=><button key={kind} disabled={frozen} onClick={()=>addEvent(kind)}><strong>+ {item.title}</strong><span>{item.description}</span></button>)}</div>{a.events.length>0&&<div className="event-tabs" aria-label="Your labels">{a.events.map((e:any,i:number)=><button key={e.id} className={target===e.id?'active':''} onClick={()=>chooseRole(e.id,'EVENT_ANCHOR')}>{i+1}. {kinds[e.kind].title}<span>{missingRoles(a,e).length?'Needs words':'Evidence added'}</span></button>)}</div>}
    {ev?<div className="event-editor"><div className="section-heading"><h3>{kinds[ev.kind].title}</h3><button className="quiet" disabled={frozen} onClick={()=>removeEvent(ev.id)}>Remove label</button></div><p className="example">Example: {kinds[ev.kind].example}</p><div className="form-row"><label>What is happening?<select disabled={frozen} value={ev.state} onChange={e=>edit(x=>x.events.find((z:any)=>z.id===ev.id).state=e.target.value)}>{eventStates[ev.kind].map(s=><option key={s} value={s}>{stateLabels[s]||human(s)}</option>)}</select></label><label>How clear is this label?<select disabled={frozen} value={ev.certainty} onChange={e=>edit(x=>{x.events.find((z:any)=>z.id===ev.id).certainty=e.target.value;if(e.target.value==='UNCERTAIN')x.needs_review=true;})}><option value="SUPPORTED">Clear from the words</option><option value="UNCERTAIN">Not sure — another review</option></select></label></div>
    {ev.kind==='ACTION'&&<label>What kind of task?<select disabled={frozen} value={ev.action_class} onChange={e=>edit(x=>{x.events.find((z:any)=>z.id===ev.id).action_class=e.target.value;if(['OTHER','UNCERTAIN'].includes(e.target.value))x.needs_review=true;})}>{[['OPERATIONAL','Do a piece of work'],['DEPARTMENTAL_CONTRIBUTION','Ask a department for input'],['DOCUMENT_TRANSFER','Document transfer (usually use Document instead)'],['APPROVAL_TRANSACTION','Approval task (check whether Approval fits)'],['OTHER','Other — needs review'],['UNCERTAIN','Not sure — needs review']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
    {ev.kind==='DOCUMENT'&&<label>Is this a project deliverable?<select disabled={frozen} value={ev.document_class} onChange={e=>edit(x=>{x.events.find((z:any)=>z.id===ev.id).document_class=e.target.value;if(e.target.value!=='PROJECT_DELIVERABLE')x.needs_review=true;})}><option value="PROJECT_DELIVERABLE">Yes — a project report or deliverable</option><option value="OTHER">A different kind of document — review</option><option value="UNCERTAIN">Not sure — review</option></select></label>}
    <h4>Required words <span>{missing.length?'Add '+missing.length+' more':'Complete'}</span></h4><div className="role-checks">{rules.required_event_roles[ev.kind].map((r:string)=><button key={r} className={role===r?'active':''} onClick={()=>chooseRole(ev.id,r)}><strong>{roleLabels[r]}</strong><span>{missing.includes(r)?'Highlight this':'Added — select to edit'}</span></button>)}</div>
    {role!=='EVENT_ANCHOR'&&rules.required_event_roles[ev.kind].includes(role)&&!a.event_span_links.some((l:any)=>l.event_id===ev.id&&l.role===role)&&a.event_span_links.some((l:any)=>l.event_id===ev.id&&l.role==='EVENT_ANCHOR')&&<div className="same-words"><p className="hint">If your first phrase also describes {role==='ACTION'?'the complete task':'the actual update'}, you can use it again. Otherwise highlight a more complete phrase.</p>{a.event_span_links.filter((l:any)=>l.event_id===ev.id&&l.role==='EVENT_ANCHOR').map((l:any)=>{const s=a.spans.find((s:any)=>s.id===l.span_id);return s?<button key={l.span_id} onClick={()=>add({field:s.field,start:s.start,end:s.end,text:s.text},role)}>Use “{s.text}” here too</button>:null;})}</div>}
    <details className="optional-details"><summary>Other details, only if mentioned</summary><p className="hint">Leave unstated facts blank. Dates and people must belong to this label.</p><div className="optional-roles">{roles.filter(r=>!rules.required_event_roles[ev.kind].includes(r)).map(r=><button key={r} className={role===r?'active':''} onClick={()=>chooseRole(ev.id,r)}>{roleLabels[r]}</button>)}</div></details>
    {rules.role_types[role][0]==='ACTOR'&&<label>What kind of name is it?<select disabled={frozen||role==='CONTRIBUTOR'} value={role==='CONTRIBUTOR'?'DEPARTMENT':actor} onChange={e=>K(e.target.value)}>{[['PERSON','A person'],['GROUP','A group or team'],['DEPARTMENT','A department'],['ROLE','A job role']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>}
    <div className="links">{a.event_span_links.filter((l:any)=>l.event_id===ev.id).map((l:any)=><div className="link" key={l.role+l.span_id}><small>{roleLabels[l.role]}</small><span>{a.spans.find((s:any)=>s.id===l.span_id)?.text}</span><button disabled={frozen} aria-label={'Remove '+roleLabels[l.role]+' evidence'} onClick={()=>edit(x=>x.event_span_links=x.event_span_links.filter((z:any)=>!(z.event_id===l.event_id&&z.span_id===l.span_id&&z.role===l.role)))}>×</button></div>)}</div>{evidenceTools}
    <details><summary>Does this explicitly follow up on an earlier act?</summary><p className="hint">“Re:” alone is not a follow-up. Highlight current reminder words. The earlier event needs another review before it can be linked.</p><button disabled={frozen||!selected||selected.field!=='current_message'} onClick={flagFollowUp}>Flag highlighted reminder for review</button>{a.event_relations.filter((r:any)=>r.source_event_id===ev.id).map((r:any)=><p key={r.id}>Earlier event {r.target?'is linked':'needs verification'} <button disabled={frozen} onClick={()=>edit(x=>x.event_relations=x.event_relations.filter((z:any)=>z.id!==r.id))}>Remove follow-up link</button></p>)}</details></div>:<div className="tip-box"><strong>{a.events.length?'Choose one of your labels above.':'No labels added yet'}</strong><p>Choose a label only when the author explicitly expresses it. If there is no act to label, you can continue with no labels.</p></div>}</>}
    <div className="step-actions"><button onClick={()=>{setStep(0);G('scope');V(null);}}>Back</button><button className="primary" onClick={()=>{setStep(2);V(null);}}>Check my review</button></div></div>}
    {step===2&&<div className="step-content"><h2>{frozen?'Your submitted review':'Check your review'}</h2><div className="review-summary"><div><span>Project relevance</span><strong>{a.scope.value==='PROJECT'?'Project work':a.scope.value==='NON_PROJECT'?'Not project work':'Not sure'}</strong><p>{a.scope.reason||'Add a reason in Relevance.'}</p></div><div><span>Message labels</span>{a.events.length?a.events.map((e:any)=><button key={e.id} onClick={()=>{setStep(1);chooseRole(e.id,'EVENT_ANCHOR');}}>{kinds[e.kind].title} · {stateLabels[e.state]||human(e.state)}</button>):<p>No project acts labeled.</p>}</div></div>
    <section className="derived-preview" aria-labelledby="derived-label-heading"><div><h3 id="derived-label-heading">Derived FYP labels</h3><p className="hint">Calculated automatically from your events and their linked evidence.</p></div>{a.needs_review?<p className="derived-empty">Labels are held until the review question is resolved.</p>:errors.length?<p className="derived-empty">Complete the required evidence and source checks to see the labels.</p>:derivedLabels.length?<ul>{derivedLabels.map((label:string)=><li key={label}><strong>{label}</strong><span>{derivedLabelHelp[label]}</span></li>)}</ul>:<p className="derived-empty">No FYP labels follow from this review yet.</p>}<p className="derived-note">If a label looks wrong, edit the event or the evidence attached to it, or flag the review. You cannot edit these labels directly.</p></section>
    {!frozen&&<>{errors.length?<div className="check-errors"><strong>Before submitting</strong><ul>{errors.map((message:string,i:number)=><li key={i}>{friendlyError(message)}</li>)}</ul><p className="hint">Return to Relevance or Label message to make a correction.</p></div>:<p className="ready-note">Your evidence matches the source and the required fields are complete. Review the meaning yourself before submitting.</p>}
    <label className="check"><input type="checkbox" checked={a.needs_review} onChange={e=>edit(x=>{x.needs_review=e.target.checked;if(!e.target.checked)x.review_reasons=[];})}/>Something needs another review</label>{a.needs_review&&<label>What are you unsure about?<textarea disabled={frozen} value={a.review_reasons.join('\n')} onChange={e=>edit(x=>x.review_reasons=e.target.value.split('\n').filter(s=>s.trim()))} placeholder="Explain the unclear project link, label, name, date, or earlier event. One issue per line."/></label>}
    <label className="check"><input type="checkbox" checked={attest} onChange={e=>C(e.target.checked)}/>I read and labeled this email independently, without AI or teammate answers.</label><p className="hint">Submitting locks this answer for independent comparison. A saved draft stays editable.</p><div className="step-actions"><button onClick={()=>{setStep(a.scope.value==='NON_PROJECT'?0:1);V(null);}}>Back to edit</button><button disabled={busy} onClick={()=>void save()}>Save draft</button><button className="primary" disabled={busy||errors.length>0||!attest} onClick={()=>void submitNext()}>Submit & next email</button></div></>}
    {frozen&&<div className="step-actions"><button className="primary" disabled={!nextEmail||busy} onClick={()=>nextEmail&&void open(nextEmail.id)}>{nextEmail?'Next unfinished email':'All assigned emails submitted'}</button></div>}</div>}
    </section></div>:<section className="empty"><h1>{busy?'Opening your email…':'Your review queue'}</h1><p>{queue.length?'Choose an email to begin.':'No emails are assigned yet. Your saved work will appear here when available.'}</p></section>}
  </main>}
  <dialog ref={guideDialog} onClose={()=>R(false)} className="help-dialog"><div className="dialog-heading"><div><span className="eyebrow">Labeling help</span><h2>Read, label, check.</h2></div><button onClick={()=>R(false)} autoFocus>Close</button></div><p className="hint">These are general examples, not answers to your assigned emails.</p>{guide.map(([title,text],i)=><details key={title} open={i<4}><summary>{title}</summary><p>{text}</p></details>)}<p className="rules-note">Leaving an unstated detail blank is better than guessing. Work independently.</p></dialog>
 </div>;
}
