import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import Module from 'node:module';
import ts from 'typescript';
const filename=path.resolve('lib/annotation.ts');
const js=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true,resolveJsonModule:true,target:ts.ScriptTarget.ES2022}}).outputText;
const mod=new Module(filename);mod.filename=filename;mod.paths=Module._nodeModulePaths(path.dirname(filename));mod._compile(js,filename);
const {validateAnnotation,deriveLabels,stampBlindHumanSubmission,stampUnannotatedDraft,cp}=mod.exports;
const fixtures=JSON.parse(fs.readFileSync('tests/synthetic-examples.json','utf8'));
let passed=0;
for(const f of fixtures){const source={...f.source,context_sources:f.context_sources||[],context_annotations:f.context_annotations||(f.context_sources||[]).map(x=>({current_source_id:x.source_id,events:x.events||[]}))};const errs=validateAnnotation(f.annotation,source);assert.deepEqual(errs,[],`${f.fixture_id}: ${errs.join('; ')}`);assert.deepEqual(deriveLabels(f.annotation),f.expected_derived_labels,`${f.fixture_id}: derived labels`);passed+=2;}
const f=fixtures.find(x=>x.annotation.events.length&&x.annotation.scope.value==='PROJECT'&&!x.annotation.needs_review);
const source={...f.source,context_sources:f.context_sources||[],context_annotations:f.context_annotations||(f.context_sources||[]).map(x=>({current_source_id:x.source_id,events:x.events||[]}))};
function rejects(mutation){const a=structuredClone(f.annotation);mutation(a);assert.ok(validateAnnotation(a,source).length);passed++;}
rejects(a=>a.scope.evidence_span_ids=[]);
rejects(a=>a.spans[0].start+=1);
rejects(a=>a.event_span_links=a.event_span_links.filter(x=>x.role!=='EVENT_ANCHOR'));
rejects(a=>{const id=a.event_span_links.find(x=>x.role==='EVENT_ANCHOR').span_id;a.spans.find(x=>x.id===id).field='subject';});
rejects(a=>a.spans.push({...a.spans[0],id:'duplicate'}));
rejects(a=>{a.scope.value='NON_PROJECT';});
rejects(a=>a.events[0].certainty='UNCERTAIN');
rejects(a=>a.provenance.annotation_tier='GOLD');
assert.equal(cp('🙂é').length,2);passed++;
const priorFixture=fixtures.find(x=>x.annotation.event_relations.some(r=>r.kind==='SUPERSEDES'&&r.target));
const priorSource={...priorFixture.source,context_sources:structuredClone(priorFixture.context_sources||[]),context_annotations:structuredClone(priorFixture.context_annotations||(priorFixture.context_sources||[]).map(x=>({current_source_id:x.source_id,events:x.events||[]})))};
const priorEvent=priorSource.context_annotations.find(x=>x.current_source_id===priorFixture.annotation.event_relations[0].target.source_id).events.find(x=>x.id===priorFixture.annotation.event_relations[0].target.event_id);priorEvent.kind='ACTION';assert.ok(validateAnnotation(priorFixture.annotation,priorSource).length);passed++;
const cleanPriorSource={...priorFixture.source,context_sources:priorFixture.context_sources||[],context_annotations:priorFixture.context_annotations||(priorFixture.context_sources||[]).map(x=>({current_source_id:x.source_id,events:x.events||[]}))};assert.deepEqual(validateAnnotation(priorFixture.annotation,cleanPriorSource),[]);const duplicateRelation=structuredClone(priorFixture.annotation);duplicateRelation.event_relations.push({...duplicateRelation.event_relations[0],id:'different-relation-id'});assert.ok(validateAnnotation(duplicateRelation,cleanPriorSource).length);passed++;
rejects(a=>{a.provenance={data_origin:'UNKNOWN',source_reference:null,synthetic_case_id:null,annotation_tier:'GOLD',annotation_mode:'BLIND_HUMAN',annotator_id:'synthetic-reviewer',annotated_at:'2026-10-01T00:00:00Z',blind_prelabels_shown:false,human_review:{reviewer_id:'synthetic-adjudicator',reviewed_at:'2026-10-01T01:00:00Z',decision:'accepted'},ai_assistance:null};});
rejects(a=>{a.provenance={data_origin:'PUBLIC_CORPUS',source_reference:source.source_id,synthetic_case_id:null,annotation_tier:'UNSET',annotation_mode:'RULE_BASED',annotator_id:null,annotated_at:null,blind_prelabels_shown:null,human_review:null,ai_assistance:null};});
const completedAction=structuredClone(fixtures.find(x=>x.fixture_id==='completed_action_is_status'));completedAction.annotation.events[0].kind='ACTION';completedAction.annotation.events[0].state='completed';completedAction.annotation.events[0].action_class='OPERATIONAL';const statusEvidence=completedAction.annotation.event_span_links.find(x=>x.role==='STATUS');completedAction.annotation.spans.find(x=>x.id===statusEvidence.span_id).type='ACTION';statusEvidence.role='ACTION';const completedSource={...completedAction.source,context_sources:[],context_annotations:[]};assert.deepEqual(validateAnnotation(completedAction.annotation,completedSource),[]);assert.deepEqual(deriveLabels(completedAction.annotation),[]);completedAction.annotation.derived_label_version='fyp-derived-labels-1.1';assert.deepEqual(validateAnnotation(completedAction.annotation,completedSource),[]);assert.deepEqual(deriveLabels(completedAction.annotation),['GENERAL_UPDATE']);passed++;
const deliveredDocument=structuredClone(fixtures.find(x=>x.fixture_id==='document_delivery_not_request'));deliveredDocument.annotation.events[0].kind='DOCUMENT';deliveredDocument.annotation.events[0].state='delivered';deliveredDocument.annotation.events[0].document_class='PROJECT_DELIVERABLE';deliveredDocument.annotation.event_span_links=deliveredDocument.annotation.event_span_links.filter(x=>x.role!=='STATUS');const deliveredSource={...deliveredDocument.source,context_sources:[],context_annotations:[]};assert.deepEqual(validateAnnotation(deliveredDocument.annotation,deliveredSource),[]);assert.deepEqual(deriveLabels(deliveredDocument.annotation),[]);deliveredDocument.annotation.derived_label_version='fyp-derived-labels-1.1';assert.deepEqual(validateAnnotation(deliveredDocument.annotation,deliveredSource),[]);assert.deepEqual(deriveLabels(deliveredDocument.annotation),['GENERAL_UPDATE']);passed++;
const reviewFixture=fixtures.find(x=>x.annotation.events.length&&x.annotation.scope.value==='PROJECT'&&!x.annotation.needs_review&&!x.annotation.event_relations.length);const reviewSource={...reviewFixture.source,source_id:reviewFixture.annotation.current_source_id};
const submitted=stampBlindHumanSubmission(reviewFixture.annotation,reviewSource,'private-reviewer-id','2026-10-06T00:00:00.000Z');assert.deepEqual(validateAnnotation(submitted,{...reviewSource,context_sources:[],context_annotations:[]}),[]);assert.equal(submitted.derived_label_version,'fyp-derived-labels-1.1');assert.equal(submitted.provenance.annotation_tier,'UNSET');assert.equal(submitted.provenance.annotation_mode,'BLIND_HUMAN');assert.equal(submitted.provenance.blind_prelabels_shown,false);assert.equal(submitted.provenance.human_review,null);passed++;
const forgedDraftInput=structuredClone(reviewFixture.annotation);forgedDraftInput.provenance={...forgedDraftInput.provenance,annotation_tier:'GOLD',annotation_mode:'AI_ONLY',annotator_id:'forged',annotated_at:'2026-10-01T00:00:00Z',ai_assistance:{human_disposition:'accepted'},blind_prelabels_shown:true};const safeDraft=stampUnannotatedDraft(forgedDraftInput,reviewSource,'fyp-derived-labels-1.0');assert.deepEqual(validateAnnotation(safeDraft,{...reviewSource,context_sources:[],context_annotations:[]}),[]);assert.equal(safeDraft.derived_label_version,'fyp-derived-labels-1.0');assert.equal(safeDraft.provenance.annotation_tier,'UNSET');assert.equal(safeDraft.provenance.annotation_mode,'UNANNOTATED');assert.equal(safeDraft.provenance.annotator_id,null);assert.equal(safeDraft.provenance.ai_assistance,null);passed++;
const oldDraftInput=structuredClone(reviewFixture.annotation);oldDraftInput.derived_label_version='fyp-derived-labels-1.0';const oldDraftSubmitted=stampBlindHumanSubmission(oldDraftInput,reviewSource,'private-reviewer-id','2026-10-06T00:00:00.000Z','fyp-derived-labels-1.0');assert.equal(oldDraftSubmitted.derived_label_version,'fyp-derived-labels-1.0');assert.deepEqual(deriveLabels(oldDraftSubmitted),deriveLabels(oldDraftInput));const unversioned=structuredClone(reviewFixture.annotation);delete unversioned.derived_label_version;const legacySubmitted=stampBlindHumanSubmission(unversioned,reviewSource,'private-reviewer-id','2026-10-06T00:00:00.000Z','fyp-derived-labels-1.0');assert.equal(legacySubmitted.derived_label_version,'fyp-derived-labels-1.0');passed++;
const syntheticSource={...reviewSource,source_id:'synthetic-case-source',data_origin:'SYNTHETIC',synthetic_case_id:'case-1'},syntheticAnnotation=structuredClone(reviewFixture.annotation);syntheticAnnotation.record_id=syntheticSource.source_id;syntheticAnnotation.current_source_id=syntheticSource.source_id;for(const span of syntheticAnnotation.spans)span.source_id=syntheticSource.source_id;
const syntheticSubmitted=stampBlindHumanSubmission(syntheticAnnotation,syntheticSource,'private-reviewer-id','2026-10-06T00:00:00.000Z');assert.deepEqual(validateAnnotation(syntheticSubmitted,{...syntheticSource,context_sources:[],context_annotations:[]}),[]);assert.equal(syntheticSubmitted.provenance.annotation_tier,'SYNTHETIC');assert.notEqual(syntheticSubmitted.provenance.annotation_tier,'GOLD');passed++;
console.log(JSON.stringify({synthetic_fixtures:fixtures.length,validation_checks:passed,derived_label_fixtures:fixtures.length,real_emails_read:0}));


