import schemaFile from './schema.json';
export const schema:any=schemaFile;
export const rules:any=schema['x-semantics'];
export const eventStates:Record<string,string[]>={MEETING:['proposed','scheduled','rescheduled','cancelled','completed'],ACTION:['requested','assigned','committed','completed','cancelled'],DOCUMENT:['requested','expected','submitted','delivered','missing','reviewed'],APPROVAL:['requested','granted','rejected','withheld','conditional'],STATUS:['progress','completed','blocker','decision','work_state_change']};
export const roleNames:Record<string,string>={EVENT_ANCHOR:'Event words',ACTION:'Action to perform',DOCUMENT:'Document',RESPONSIBLE_PARTY:'Responsible person/team',CONTRIBUTOR:'Contributing department/team',RECIPIENT:'Recipient',MENTION_ONLY:'Mentioned person only',PARTICIPANT:'Meeting participant',MEETING_NAME:'Meeting name',LOCATION:'Meeting location',MEETING_DATE:'Meeting date',MEETING_TIME:'Meeting time',DUE_DATE:'Due date',DUE_TIME:'Due time',OCCURRENCE_DATE:'Other event date',OCCURRENCE_TIME:'Other event time',APPROVAL_TARGET:'What is approved',APPROVER:'Approver',STATUS:'Status words',AGENDA:'Meeting agenda',PROJECT:'Project name'};
export const cp=(s:string)=>Array.from(s);
export function blank(source:any){return {schema_version:'fyp-structured-v1',record_id:source.source_id,current_source_id:source.source_id,scope:{value:'UNCERTAIN',evidence_span_ids:[],reason:''},spans:[],events:[],event_span_links:[],event_relations:[],needs_review:false,review_reasons:[],provenance:{data_origin:source.data_origin,source_reference:source.source_id,synthetic_case_id:null,annotation_tier:'UNSET',annotation_mode:'UNANNOTATED',annotator_id:null,annotated_at:null,blind_prelabels_shown:null,human_review:null,ai_assistance:null}};}
function structural(v:any,s:any,p='$'):string[]{
 if(s===true)return [];if(s===false)return [p+' is forbidden'];let e:string[]=[];
 if(s.$ref)e.push(...structural(v,s.$ref.split('/').slice(1).reduce((a:any,k:string)=>a[k],schema),p));
 if('const'in s&&JSON.stringify(v)!==JSON.stringify(s.const))e.push(p+' has an invalid value');
 if(s.enum&&!s.enum.some((x:any)=>JSON.stringify(x)===JSON.stringify(v)))e.push(p+' has an invalid choice');
 if(s.type){const ts=Array.isArray(s.type)?s.type:[s.type];if(!ts.some((t:string)=>t==='null'?v===null:t==='array'?Array.isArray(v):t==='object'?v!==null&&typeof v==='object'&&!Array.isArray(v):t==='integer'?Number.isInteger(v):typeof v===t))return [...e,p+' has an invalid type'];}
 if(typeof v==='string'){if(s.minLength&&cp(v).length<s.minLength)e.push(p+' is required');if(s.format==='date-time'&&!/^\d{4}-\d{2}-\d{2}T.+(?:Z|[+-]\d{2}:\d{2})$/.test(v))e.push(p+' needs an ISO timestamp');}
 if(typeof v==='number'&&s.minimum!==undefined&&v<s.minimum)e.push(p+' is below the minimum');
 if(Array.isArray(v)){if(s.minItems!==undefined&&v.length<s.minItems)e.push(p+' needs evidence');if(s.maxItems!==undefined&&v.length>s.maxItems)e.push(p+' has too many items');if(s.uniqueItems&&new Set(v.map(x=>JSON.stringify(x))).size!==v.length)e.push(p+' contains duplicates');if(s.items)v.forEach((x,i)=>e.push(...structural(x,s.items,`${p}[${i}]`)));}
 if(v!==null&&typeof v==='object'&&!Array.isArray(v)){for(const k of s.required||[])if(!(k in v))e.push(p+'.'+k+' is required');for(const [k,x]of Object.entries(v)){if(s.properties?.[k])e.push(...structural(x,s.properties[k],p+'.'+k));else if(s.additionalProperties===false)e.push(p+'.'+k+' is not allowed');}}
 if(s.allOf)for(const x of s.allOf)e.push(...structural(v,x,p));
 if(s.oneOf&&s.oneOf.filter((x:any)=>structural(v,x,p).length===0).length!==1)e.push(p+' does not match exactly one allowed record');
 if(s.anyOf&&!s.anyOf.some((x:any)=>structural(v,x,p).length===0))e.push(p+' does not match an allowed value');
 if(s.not&&structural(v,s.not,p).length===0)e.push(p+' has a forbidden combination');
 if(s.if){const branch=structural(v,s.if,p).length===0?s.then:s.else;if(branch)e.push(...structural(v,branch,p));}return e;
}
export function validateAnnotation(a:any,source:any):string[]{
 let errors=structural(a,schema);if(errors.length)return errors.slice(0,20);const fail=(s:string)=>errors.push(s);
 if(a.current_source_id!==source.source_id)fail('Wrong current email.');
 const sources=new Map<string,any>([[source.source_id,source],...(source.context_sources||[]).map((x:any)=>[x.source_id,x])]);
 const spans=new Map<string,any>(),events=new Map<string,any>();const allIds=new Set<string>();for(const x of [...a.spans,...a.events,...a.event_relations]){if(allIds.has(x.id))fail('Evidence/event/relation IDs must be globally unique.');allIds.add(x.id);}const coords=new Set<string>();
 for(const s of a.spans){if(spans.has(s.id))fail('Duplicate evidence ID.');spans.set(s.id,s);const src=sources.get(s.source_id);const text=src?.[s.field];if(typeof text!=='string'||s.end<=s.start||s.end>cp(text).length||cp(text).slice(s.start,s.end).join('')!==s.text)fail(`Evidence ${s.id} must exactly match its source.`);const key=JSON.stringify([s.source_id,s.field,s.type,s.start,s.end]);if(coords.has(key))fail('Share existing evidence instead of duplicating it.');coords.add(key);if(s.source_id!==source.source_id)fail('Evidence must belong to the current email.');if(s.field==='current_message'&&!(src?.authored_ranges||[]).some((r:any)=>s.start>=r.start&&s.end<=r.end))fail(`Evidence ${s.id} is outside the authored message.`);}
 for(const id of a.scope.evidence_span_ids){const s=spans.get(id);if(!s||s.source_id!==source.source_id)fail('Project relevance needs evidence from this email.');}
 for(const e of a.events){if(events.has(e.id))fail('Duplicate event ID.');events.set(e.id,e);}
 const linkKeys=new Set();for(const l of a.event_span_links){const e=events.get(l.event_id),s=spans.get(l.span_id);if(!e||!s){fail('An evidence link has no matching event/span.');continue;}if(!rules.role_types[l.role]?.includes(s.type)||!rules.role_event_kinds[l.role]?.includes(e.kind))fail(`${roleNames[l.role]||l.role} is incompatible with this event/evidence.`);if(rules.role_actor_kind?.[l.role]&&!rules.role_actor_kind[l.role].includes(s.actor_kind))fail('This role requires a department actor.');if(l.role==='EVENT_ANCHOR'&&(s.source_id!==source.source_id||s.field!=='current_message'))fail('Event words must be in the current authored message.');const k=JSON.stringify([l.event_id,l.span_id,l.role]);if(linkKeys.has(k))fail('Duplicate evidence link.');linkKeys.add(k);}
 for(const e of a.events){const links=a.event_span_links.filter((l:any)=>l.event_id===e.id);for(const role of rules.required_event_roles[e.kind])if(!links.some((l:any)=>l.role===role))fail(`${e.kind} ${e.id} needs ${roleNames[role]}.`);}
 const relationIds=new Set(),relationKeys=new Set();for(const r of a.event_relations){if(relationIds.has(r.id))fail('Duplicate relation ID.');relationIds.add(r.id);if(!events.has(r.source_event_id))fail('Relation has no current event.');for(const id of r.evidence_span_ids){const s=spans.get(id);if(!s||s.source_id!==source.source_id||s.field!=='current_message')fail('Thread relation needs current authored evidence.');}if(!a.event_span_links.some((l:any)=>l.event_id===r.source_event_id&&l.role==='EVENT_ANCHOR'&&r.evidence_span_ids.includes(l.span_id)))fail('Thread relation evidence must include its current event words.');if(r.target?.source_id===source.source_id)fail('Thread target must be an earlier source.');if(r.target&&!sources.has(r.target.source_id))fail('Prior source is absent.');if(r.target){const prior=(source.context_annotations||[]).find((x:any)=>x.current_source_id===r.target.source_id)?.events?.find((e:any)=>e.id===r.target.event_id);if(!prior)fail('Prior event target has not been independently resolved.');else if(r.kind==='SUPERSEDES'&&prior.kind!==events.get(r.source_event_id)?.kind)fail('A superseding event must replace a prior event of the same kind.');const key=JSON.stringify([r.source_event_id,r.kind,r.target.source_id,r.target.event_id]);if(relationKeys.has(key))fail('Share an existing relation instead of duplicating it.');relationKeys.add(key);}}
 const p=a.provenance;if(p.annotation_tier==='GOLD'&&(!['REAL_EMAIL','PUBLIC_CORPUS'].includes(p.data_origin)||p.human_review?.decision==='rejected'))fail('Gold requires an accepted human review of a real source.');if(p.annotation_mode==='RULE_BASED'&&(p.annotation_tier!=='SILVER'||p.ai_assistance!==null))fail('Rule-based annotations must be silver without model-assistance claims.');
 if(a.scope.value==='NON_PROJECT'&&(a.events.length||a.event_span_links.length||a.event_relations.length))fail('Not project related must have no project events or relations.');
 const uncertain=a.scope.value==='UNCERTAIN'||a.events.some((e:any)=>e.certainty==='UNCERTAIN'||rules.review_classes.action_class.includes(e.action_class)||rules.review_classes.document_class.includes(e.document_class))||a.event_span_links.some((l:any)=>l.certainty==='UNCERTAIN')||a.event_relations.some((r:any)=>r.certainty==='UNCERTAIN'||!r.target);
 if(uncertain&&!a.needs_review)fail('Uncertainty or unresolved prior events require another review.');if(a.needs_review&&!a.review_reasons.length)fail('Explain what needs another review.');if(!a.needs_review&&a.review_reasons.length)fail('Clear review notes or select Needs another review.');return [...new Set(errors)].slice(0,20);
}
