export const labelGuide:Record<string,{title:string;description:string;example:string;fields:string[];required:string[]}>= {
 MEETING:{title:'Meeting',description:'Arrange, confirm, change, cancel or discuss a specific project meeting, call or workshop.',example:'“Project review is Friday at 3.” Meeting only; Friday is not a deadline.',fields:['MEETING_DATE','MEETING_TIME','PARTICIPANT','AGENDA','PROJECT'],required:[]},
 DEADLINE:{title:'Deadline',description:'State or follow up a due date or time for project work or a deliverable.',example:'“Send the draft by Friday.” Mark Friday as the deadline and say what is due.',fields:['DEADLINE_DATE','DEADLINE_TIME','ACTION_ITEM','REQUESTED_DOCUMENT'],required:[]},
 REPORT_REQUEST:{title:'Report / document request',description:'Ask for, expect or chase a formal project report, plan, draft or deliverable.',example:'“Please send the revised report.” Report request. “The report was sent” is General update.',fields:['REQUESTED_DOCUMENT','RESPONSIBLE_PARTY','PROJECT'],required:[]},
 DEPARTMENTAL_INPUT:{title:'Departmental input',description:'Request, track or report a contribution, data, feedback or decision from an organizational unit.',example:'“Finance, please send the figures.” Departmental input; simply mentioning Finance does not count.',fields:['DEPARTMENT','ACTION_ITEM','REQUESTED_DOCUMENT','RESPONSIBLE_PARTY'],required:[]},
 ACTION_REQUEST:{title:'Action request',description:'Ask for a distinct operational task, such as testing, fixing, checking or reviewing.',example:'“Please test the system and send the report.” Action request + Report request. Sending the report alone is not a separate action.',fields:['ACTION_ITEM','RESPONSIBLE_PARTY'],required:[]},
 FOLLOW_UP:{title:'Follow-up',description:'Remind, chase, check or escalate something that was already expected.',example:'“Reminder: we still need your report.” Follow-up + Report request. A first request or “Re:” alone is not follow-up.',fields:['ACTION_ITEM','REQUESTED_DOCUMENT','DEPARTMENT','RESPONSIBLE_PARTY'],required:[]},
 APPROVAL:{title:'Approval',description:'Request or communicate formal approval, sign-off or authorization, including rejection or conditions.',example:'“Please review the draft” is Action request. “Please approve the draft” is Approval. “The draft is approved” is Approval + General update.',fields:['REQUESTED_DOCUMENT','ACTION_ITEM','RESPONSIBLE_PARTY','PROJECT'],required:[]},
 GENERAL_UPDATE:{title:'General update',description:'Communicate meaningful progress, completion, a blocker, decision or change in project work.',example:'“Testing is complete.” General update. Giving background information alone is not enough.',fields:['ACTION_ITEM','REQUESTED_DOCUMENT','PROJECT'],required:[]}
};
export const fieldNames:Record<string,string>={EVIDENCE:'Words that show this label',MEETING_DATE:'Meeting date',MEETING_TIME:'Meeting time',DEADLINE_DATE:'Due date',DEADLINE_TIME:'Due time',ACTION_ITEM:'What work / action',RESPONSIBLE_PARTY:'Who is responsible',DEPARTMENT:'Department or unit',REQUESTED_DOCUMENT:'Requested document',PARTICIPANT:'Who attends',AGENDA:'Meeting agenda',PROJECT:'Project name'};
export const directGuide:[string,string][]=[
 ['1. Read the current author’s words','Label the current message. The subject and older thread help you understand it. Faded signatures and quoted history cannot establish a new label. Work independently; no AI or teammate answers.'],
 ['2. Decide project relevance','Project work has a bounded initiative, coordinated workstream, milestone or deliverable. A routine business request is not automatically project work. Choose Not sure when the connection is missing.'],
 ['3. Choose every FYP label that applies','You choose the final labels directly. There is no hidden label mapper. Multiple labels are allowed. A project message with none of these functions needs another review; do not force General update.'],
 ...Object.entries(labelGuide).map(([label,g]):[string,string]=>[g.title+' · '+label,g.description+' '+g.example]),
 ['Requests can overlap, but do not double-count actions','A report due Friday is Report request + Deadline. Finance asking for figures due Thursday is Departmental input + Deadline. Add Report request only for an identified formal deliverable, and Action request only for a separate operational task. Ordinary draft review is an operational task; formal sign-off is Approval.'],
 ['Updates alongside other labels','Select Approval + General update for a communicated approval decision. Select Deadline + General update for an explicit changed due date. Select Departmental input + General update for a completed/submitted contribution. A future request alone is not an update. These labels are chosen by you, never added automatically.'],
 ['Evidence: label first, highlight second','For each label, highlight current words showing that function. Then add any of the 11 extraction fields only where explicitly stated. These fields are optional; absent dates, documents or names do not invalidate a clear label. EVIDENCE is auxiliary support, not a 12th extraction target. One phrase can support several labels. Use the same words again for fields when appropriate. Meeting dates belong to Meeting; due dates belong to Deadline.'],
 ['Unclear details','Highlight the current words that support your label. Flag genuine uncertainty about scope, label meaning or an unresolved thread reference. Do not flag a clear label merely because a date, person or target is not written. Needs review preserves a tentative judgment; it cannot silently become gold. If you cannot justify project relevance, choose Not sure.'],
 ['Names and dates need a function','A date alone is not a deadline. Extract RESPONSIBLE_PARTY only when the words assign responsibility, not whenever a person is named. Department mentions do not establish departmental input. Missing arguments can be left blank.'],
 ['Submitting','Drafts autosave and remain editable. Submission locks your independent answer. Human labels are not gold until independent comparison and adjudication. Legacy drafts keep their original schema and rules.']
];
